"""create_user_examination_table

Revision ID: 0952314181f2
Revises: a139e6be862e
Create Date: 2026-09-10 16:31:48.687435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0952314181f2'
down_revision: Union[str, Sequence[str], None] = 'a139e6be862e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_examination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('total_question', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('total_questions_answered', sa.Integer(), nullable=False),
    sa.Column('total_questions_failed', sa.Integer(), nullable=False),
    sa.Column('questions_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('correct_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('failed_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('exam_year', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_examination_id'), 'user_examination', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_examination_id'), table_name='user_examination')
    op.drop_table('user_examination')
    # ### end Alembic commands ###
