"""make_user_fields_nullable

Revision ID: 560bb9cd4c5e
Revises: bd0421ac6c8d
Create Date: 2026-09-02 20:53:25.826050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560bb9cd4c5e'
down_revision: Union[str, Sequence[str], None] = 'bd0421ac6c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'UserBadge', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'UserBadge', 'badge', ['badge_id'], ['id'])
    op.create_foreign_key(None, 'activity', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'university',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'examinations',
               existing_type=postgresql.ARRAY(postgresql.ENUM('waec', 'neco', 'utme', 'jamb', name='examination')),
               nullable=True)
    op.alter_column('user', 'current_expectation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'prep_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'best_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'best_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'prep_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'current_expectation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'examinations',
               existing_type=postgresql.ARRAY(postgresql.ENUM('waec', 'neco', 'utme', 'jamb', name='examination')),
               nullable=False)
    op.alter_column('user', 'university',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'UserBadge', type_='foreignkey')
    op.drop_constraint(None, 'UserBadge', type_='foreignkey')
    # ### end Alembic commands ###
