"""change_current_examination_date_to_string

Revision ID: a139e6be862e
Revises: 40be0bb71302
Create Date: 2026-09-10 09:56:49.115867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a139e6be862e'
down_revision: Union[str, Sequence[str], None] = '40be0bb71302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'current_examination_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'current_examination_date',
               existing_type=sa.String(length=255),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
