"""add_type_and_make_fields_nullable_in_user_examination

Revision ID: c8ab5fcf7b0f
Revises: 0952314181f2
Create Date: 2026-09-10 16:42:06.617296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ab5fcf7b0f'
down_revision: Union[str, Sequence[str], None] = '0952314181f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_examination', sa.Column('type', sa.String(length=50), server_default='practice', nullable=False))
    op.alter_column('user_examination', 'total_question',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_examination', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_examination', 'time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_examination', 'time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_examination', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_examination', 'total_question',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_examination', 'type')
    # ### end Alembic commands ###
